# This file was generated by GoReleaser. DO NOT EDIT.
class Proxypool < Formula
  desc "Downloads,  checks and stores proxies from the web with rest api for querying results."
  homepage ""
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nicksherron/proxypool/releases/download/v0.1.3/proxypool_v0.1.3_darwin_amd64.tar.gz"
    sha256 "bd17c31afbd813ed1992b4bb79197b5f41607238dd2e2de5eefa226e41a1d79d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nicksherron/proxypool/releases/download/v0.1.3/proxypool_v0.1.3_linux_amd64.tar.gz"
      sha256 "8fbb4bfc9e6728354d6b8a98a1161949383a0b234c9640c9e54f1ac4fa096f09"
    end
  end

  def install
    bin.install "proxypool"
  end

  test do
    system "#{bin}/proxypool version"
  end
end
